const data = [
  {
    id: 1,
    name: "Mark Webber",
    profilePic: "/avatar-mark-webber.webp",
    notification: "reacted to your recent post",
    notificationTo: "My First Tournament today!",
    notificationTime: "1m ago",
    unRead: true,
    notificationImg: "",
    notificationMessage: "",
  },
  {
    id: 2,
    name: "Angela Gray",
    profilePic: "/avatar-angela-gray.webp",
    notification: "followed you",
    notificationTo: "",
    notificationTime: "5m ago",
    unRead: true,
    notificationImg: "",
    notificationMessage: "",
  },
  {
    id: 3,
    name: "Jacob Thompson",
    profilePic: "/avatar-jacob-thompson.webp",
    notification: "has joined your group",
    notificationTo: "Chess Club",
    notificationTime: "1 day ago",
    unRead: true,
    notificationImg: "",
    notificationMessage: "",
  },
  {
    id: 4,
    name: "Rizky Hasanuddin",
    profilePic: "/avatar-rizky-hasanuddin.webp",
    notification: "sent you a private message",
    notificationTo: "",
    notificationTime: "5 days ago",
    unRead: false,
    notificationImg: "",
    notificationMessage:
      "Hello, thanks for setting up the Chess Club. I`ve been a member for a few weeks now and I`m already having lots of fun and improving my game.",
  },
  {
    id: 5,
    name: "Kimberly Smith",
    profilePic: "/avatar-kimberly-smith.webp",
    notification: "commented on your picture",
    notificationTo: "",
    notificationTime: "1 week ago",
    unRead: false,
    notificationImg: "/image-chess.webp",
    notificationMessage: "",
  },
  {
    id: 6,
    name: "Nathan Peterson",
    profilePic: "/avatar-nathan-peterson.webp",
    notification: "reacted to your recent post",
    notificationTo: "5 end-game strategies to increase your win rate",
    notificationTime: "2 weeks ago",
    unRead: false,
    notificationImg: "",
    notificationMessage: "",
  },
  {
    id: 7,
    name: "Anna Kim",
    profilePic: "/avatar-anna-kim.webp",
    notification: "left the group",
    notificationTo: "Chess Club",
    notificationTime: "2 weeks ago",
    unRead: false,
    notificationImg: "",
    notificationMessage: "",
  },
];

export default data;
